"""Profile data/capital.duckdb and write docs/profile.md (coverage, join integrity, locations)."""
import json
import sys

import duckdb

from db import DB_PATH, ROOT
from geo import contains, haversine_m
from validation import address_agreement, district_agreement, named_feature_agreement, street_line_agreement

OUT = ROOT / "docs" / "profile.md"

TABLES = ["project_budget_schedule", "budget_spend_by_fy", "budget_history", "schedule_history"]
KEY_COLS = {
    "project_budget_schedule": ["pid", "fms_id", "managing_agency", "total_budget", "spend_to_date",
                                "current_phase", "forecast_completion", "borough", "community_board"],
    "budget_spend_by_fy": ["fms_id", "managing_agency", "fiscal_year", "total_budget_city_non_city", "spend"],
    "budget_history": ["fms_id", "managing_agency", "total_budget", "budget_variance", "budget_variance_pct"],
    "schedule_history": ["pid", "managing_agency", "completion_date", "variance_day"],
}
LOCATION_HINTS = ["lat", "lon", "lng", "geom", "the_geom", "location", "address", "bbl", "bin",
                  "borough", "community", "district", "zip", "x_coord", "y_coord", "council"]

con = duckdb.connect(str(DB_PATH), read_only=True)
lines: list[str] = []


def md(s: str = "") -> None:
    lines.append(s)


def table(sql: str) -> None:
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    rows = cur.fetchall()
    md("| " + " | ".join(cols) + " |")
    md("|" + "|".join("---" for _ in cols) + "|")
    plain = {i for i, c in enumerate(cols) if "period" in c or "year" in c or c == "pid"}  # no thousands separator
    for r in rows:
        md("| " + " | ".join(
            "" if v is None else
            str(v) if i in plain else
            f"{v:,}" if isinstance(v, int) else
            f"{v:,.2f}" if isinstance(v, float) else str(v)
            for i, v in enumerate(r)) + " |")
    md()


def scalar(sql: str):
    return con.execute(sql).fetchone()[0]


md("# Data profile")
md()
md("Generated by `pipeline/profile.py` from `data/capital.duckdb`. Re-run after each ingest.")
md()
md("## 1. Source freshness and row counts")
table("select table_name, dataset_id, source_rows_updated_at, remote_count, loaded_rows from _ingest_meta")

md("## 2. Coverage")
md("### Snapshots (reporting periods)")
md("`project_budget_schedule` and `budget_spend_by_fy` hold one full snapshot per reporting period "
   "(YYYYMM, Jan/May/Sep). `budget_history` is keyed by `year_month_reported`.")
md()
table("""select 'project_budget_schedule' t, min(reporting_period) first_period, max(reporting_period) last_period,
         count(distinct reporting_period) periods from project_budget_schedule
         union all select 'budget_spend_by_fy', min(reporting_period), max(reporting_period),
         count(distinct reporting_period) from budget_spend_by_fy
         union all select 'budget_history', min(year_month_reported), max(year_month_reported),
         count(distinct year_month_reported) from budget_history
         union all select 'schedule_history', min(reporting_period), max(reporting_period),
         count(distinct reporting_period) from schedule_history""")
md("### Per-period distinct projects (project_budget_schedule)")
table("""select reporting_period, count(*) n_rows, count(distinct fms_id) fms_ids, count(distinct pid) pids,
         round(100.0*count(pid)/count(*),1) pct_rows_with_pid from project_budget_schedule
         group by 1 order by 1""")
md("### Null rates for key columns (%)")
for t in TABLES:
    md(f"**{t}**")
    md()
    parts = ", ".join(f"round(100.0*count_if({c} is null)/count(*),1) as {c}" for c in KEY_COLS[t])
    table(f"select {parts} from {t}")
md("### Managing agencies in latest snapshot (top 15 by project count)")
table("""select managing_agency, count(distinct fms_id) fms_ids, sum(total_budget) total_budget
         from project_budget_schedule where reporting_period=(select max(reporting_period) from project_budget_schedule)
         group by 1 order by 2 desc limit 15""")

md("## 3. Join integrity")
latest = scalar("select max(reporting_period) from project_budget_schedule")
md(f"Latest snapshot used below: **{latest}**.")
md()
md("### Duplicate keys")
table("""select 'project_budget_schedule (fms_id, reporting_period)' as key_cols,
          count(*) - count(distinct (fms_id, reporting_period)) excess_rows from project_budget_schedule
          union all select 'budget_spend_by_fy (fms_id, fiscal_year, reporting_period)',
          count(*) - count(distinct (fms_id, fiscal_year, reporting_period)) from budget_spend_by_fy
          union all select 'budget_history (fms_id, year_month_reported)',
          count(*) - count(distinct (fms_id, year_month_reported)) from budget_history
          union all select 'schedule_history (pid, reporting_period)',
          count(*) - count(distinct (pid, reporting_period)) from schedule_history""")
md("### FMS ID overlap in the latest snapshot")
table(f"""with a as (select distinct fms_id from project_budget_schedule where reporting_period={latest}),
          b as (select distinct fms_id from budget_spend_by_fy where reporting_period={latest}),
          h as (select distinct fms_id from budget_history)
          select (select count(*) from a) in_project, (select count(*) from b) in_fy_spend,
                 (select count(*) from h) in_history_all_time,
                 (select count(*) from a join b using(fms_id)) project_and_fy,
                 (select count(*) from a anti join b using(fms_id)) project_not_in_fy,
                 (select count(*) from b anti join a using(fms_id)) fy_not_in_project,
                 (select count(*) from a anti join h using(fms_id)) project_not_in_history""")
md("### PID overlap (project_budget_schedule vs schedule_history), latest snapshot")
table(f"""with a as (select distinct pid from project_budget_schedule
                    where reporting_period={latest} and pid is not null),
          s as (select distinct pid from schedule_history where reporting_period={latest})
          select (select count(*) from a) pids_in_project, (select count(*) from s) pids_in_schedule_history,
                 (select count(*) from a join s using(pid)) as n_matched,
                 (select count(*) from s anti join a using(pid)) schedule_pid_not_in_project""")
md("### PID <-> FMS ID cardinality (latest snapshot, rows with a PID)")
md("Many-to-many is confirmed if both maxima exceed 1. Only `project_budget_schedule` carries both keys, "
   "so it is the bridge between FMS-keyed budget data and PID-keyed schedule history.")
md()
table(f"""with m as (select distinct pid, fms_id from project_budget_schedule
                    where reporting_period={latest} and pid is not null),
          pf as (select pid, count(*) n from m group by 1), fp as (select fms_id, count(*) n from m group by 1)
          select (select count(*) from m) pid_fms_pairs,
                 (select max(n) from pf) max_fms_per_pid, (select count_if(n>1) from pf) pids_with_multi_fms,
                 (select max(n) from fp) max_pid_per_fms, (select count_if(n>1) from fp) fms_with_multi_pid""")
md("### Rows with FMS ID but no PID (latest snapshot)")
table(f"""select count(*) rows_no_pid, count(distinct fms_id) fms_no_pid
          from project_budget_schedule where reporting_period={latest} and pid is null""")

md("### Fan-out warning: repeated FMS IDs in project_budget_schedule")
md("Repeated `fms_id` rows within a snapshot are one row per linked PID, not true duplicates. "
   "Most repeat the same budget, but some differ (see `repeated_with_differing_budget`), so de-duplication "
   "needs a rule (e.g. take the budget from `budget_spend_by_fy`/`budget_history`, which are FMS-keyed). "
   "Summing `total_budget` across rows without de-duplicating by `fms_id` double-counts. "
   "The dedup figure below uses an arbitrary row per FMS ID and is illustrative only.")
md()
table(f"""with d as (select fms_id, count(*) n, count(distinct total_budget) n_budgets
                    from project_budget_schedule where reporting_period={latest} group by 1)
          select count_if(n>1) fms_ids_repeated, max(n) max_rows_per_fms,
                 count_if(n>1 and n_budgets>1) repeated_with_differing_budget from d""")
table(f"""select round(sum(total_budget)) as naive_sum_all_rows,
          (select round(sum(b)) from (select any_value(total_budget) b from project_budget_schedule
             where reporting_period={latest} group by fms_id)) as dedup_sum_by_fms
          from project_budget_schedule where reporting_period={latest}""")

md("## 4. Variance sign sanity")
md("Variance must be reported signed. Confirm both signs exist so values were not stored as absolute.")
md()
table("""select 'budget_variance' col, count_if(budget_variance<0) negative, count_if(budget_variance=0) zero,
         count_if(budget_variance>0) positive, count_if(budget_variance is null) as n_null,
         min(budget_variance) as min_v, max(budget_variance) as max_v from budget_history
         union all select 'budget_variance_pct', count_if(budget_variance_pct<0), count_if(budget_variance_pct=0),
         count_if(budget_variance_pct>0), count_if(budget_variance_pct is null), min(budget_variance_pct),
         max(budget_variance_pct) from budget_history
         union all select 'variance_day', count_if(variance_day<0), count_if(variance_day=0),
         count_if(variance_day>0), count_if(variance_day is null), min(variance_day), max(variance_day)
         from schedule_history""")

md("### Outliers: implausible forecast dates in schedule_history")
md("Rows with |variance_day| > 3,650 (10 years) are almost certainly data-entry errors "
   "and should be excluded or clamped in the UI.")
md()
table("""select pid, completion_date, completion_date_type, variance_day from schedule_history
         where abs(variance_day) > 3650 order by abs(variance_day) desc""")

md("## 5. Location fields in the core datasets")
md("Columns in the four core tables whose name hints at a location:")
md()
hits = con.execute("select table_name, column_name, data_type from information_schema.columns "
                   f"where table_name in ({', '.join(repr(t) for t in TABLES)})").fetchall()
loc = [h for h in hits if any(k in h[1].lower() for k in LOCATION_HINTS)]
md("| table | column | type |")
md("|---|---|---|")
for t, c, d in loc:
    md(f"| {t} | {c} | {d} |")
md()
md("### Community board granularity (latest snapshot)")
md("`community_board` is free text: a specific district (`Manhattan 01`), several (`Queens, Queens 07`), "
   "a borough only (`Queens`), `Citywide`, or a borough-wide placeholder (`Brooklyn 99`).")
md()
table(f"""select count_if(community_board = 'Citywide') citywide,
          count_if(community_board is null) null_board,
          count_if(regexp_matches(community_board, '(Manhattan|Bronx|Brooklyn|Queens|Staten Island) (0[1-9]|1[0-8])'))
              as names_a_district,
          count_if(community_board in ('Manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Staten Island')) borough_only,
          count(*) total from project_budget_schedule where reporting_period={latest}""")
md("The core datasets have no coordinates, addresses, BBL/BIN or geometry, so locations come from the "
   "external sources in section 6.")
md()

md("## 6. Location enrichment (`pipeline/locations.py`)")
md("Each FMS ID gets its best available location, by tier:")
md()
md("- **A**: agency/DCP geometry joined on FMS ID: Parks capital project tracker (`4hcv-tc5r`) > "
   "CPDB points (`h2ic-zdws`) > CPDB polygon centroids (`9jkp-n57r`) > DOT/DEP intersections (`97nd-ff3i`); "
   "then street addresses in project text (Geoclient), named point/area features (gazetteer) and street "
   "extents between two cross streets (centerline). DCP notes some CPDB geometry was itself fuzzy-matched, "
   "so A is good, not exact.")
md("- **B**: linear named features (aqueducts, tunnels, corridors), a whole street within the project's "
   "district, a facility code in the FMS ID (HHC, CUNY, DCLA), a unit named in the title (FDNY, NYPD, DSNY, "
   "DOC), or the project title matched to a DCP Facilities Database (`ji82-xba5`) or Parks Properties "
   "(`enfh-gkve`) name in the same borough. Approximate; precision is measured below.")
md("- **C**: centroid of a neighborhood named in the title (DCP 2020 Neighborhood Tabulation Areas, "
   "`9nt8-h7nd`). Neighborhood-level only.")
md("- **D**: centroid of the named community district(s) (`5crt-au7u`). District-level only.")
md("- **E**: borough centroid. Borough-level only.")
md("- Unplaced: `Citywide` or no usable borough.")
md()
md("### Source rows kept (rows outside NYC bounds or without coordinates are dropped)")
md("Multi-point sources have more kept rows (one per point) than source rows.")
md()
table("""with kept as (
           select 'loc_cpdb_points' t, count(*) n, count(distinct fms_id) f from loc_cpdb_points
           union all select 'loc_cpdb_polygons', count(*), count(distinct fms_id) from loc_cpdb_polygons
           union all select 'loc_parks_tracker', count(*), count(distinct fms_id) from loc_parks_tracker
           union all select 'loc_dot_intersections', count(*), count(distinct fms_id) from loc_dot_intersections
           union all select 'ref_facilities', count(*), null from ref_facilities
           union all select 'ref_parks_properties', count(*), null from ref_parks_properties
           union all select 'ref_community_districts', count(*), null from ref_community_districts)
         select m.table_name, m.dataset_id, m.loaded_rows source_rows, k.n kept_rows, k.f fms_ids
         from _ingest_meta m join kept k on k.t = m.table_name order by m.table_name""")

latest_fms = f"""(select fms_id, any_value(managing_agency) managing_agency, any_value(total_budget) budget
                  from project_budget_schedule where reporting_period={latest} group by fms_id)"""
md(f"### Coverage by tier (latest snapshot {latest}, one row per FMS ID)")
md("Budget uses one arbitrary row per FMS ID (see the fan-out warning in section 3); illustrative only.")
md()
table(f"""select coalesce(l.tier, 'unplaced') tier, count(*) fms_ids,
          round(100.0 * count(*) / sum(count(*)) over (), 1) pct_projects,
          round(sum(p.budget) / 1e9, 1) budget_bn,
          round(100.0 * sum(p.budget) / sum(sum(p.budget)) over (), 1) pct_budget
          from {latest_fms} p left join project_locations l using (fms_id) group by 1 order by 1""")
md("### Coverage by managing agency (latest snapshot, top 15 by project count, % of FMS IDs)")
table(f"""select p.managing_agency, count(*) fms_ids,
          round(100.0 * count_if(l.tier = 'A') / count(*), 1) pct_a,
          round(100.0 * count_if(l.tier = 'B') / count(*), 1) pct_b,
          round(100.0 * count_if(l.tier = 'C') / count(*), 1) pct_c,
          round(100.0 * count_if(l.tier = 'D') / count(*), 1) pct_d,
          round(100.0 * count_if(l.tier = 'E') / count(*), 1) pct_e,
          round(100.0 * count_if(l.tier is null) / count(*), 1) pct_unplaced
          from {latest_fms} p left join project_locations l using (fms_id)
          group by 1 order by 2 desc limit 15""")
md("### Tier A source mix (all FMS IDs)")
table("""select source, count(*) fms_ids, count_if(n_points > 1) multi_point,
         count_if(spread_m > 2000 and source not like 'street_%') as spread_over_2km
         from project_locations where tier = 'A' group by 1 order by 2 desc""")
md("For street sources `spread_m` holds the line length, so they are excluded from `spread_over_2km`.")
md()

md("### Address geocoding agreement")
md("Street addresses in project text, geocoded by NYC Geoclient (exact matches in the project's borough only), "
   "compared with the other Tier A sources where a project has both. This method was not tuned on this data.")
md()
md("| compared with | projects | median_m | within_100m | within_500m |")
md("|---|---|---|---|---|")
for s, ds in sorted(address_agreement(con).items()):
    near100, near500 = sum(d <= 100 for d in ds), sum(d <= 500 for d in ds)
    md(f"| {s} | {len(ds):,} | {ds[len(ds) // 2]:,.0f} | {near100:,} | {near500:,} |")
md()

md("### Named-feature gazetteer")
md("Bridges, wastewater plants, terminals and corridors from `pipeline/named_features.csv`, located through "
   "Geoclient, official tax lots (BBL) or USGS GNIS. Agreement with other Tier A sources where a project has both:")
md()
nds = named_feature_agreement(con)
if nds:
    md(f"{len(nds)} projects compared: median {nds[len(nds) // 2]:,.0f} m, {sum(d <= 500 for d in nds)} within 500 m, "
       f"{sum(d <= 1000 for d in nds)} within 1 km (plants and bridges are large, so 500 m is strict).")
    md()
table("""select n.feature_id, n.kind, n.extent, n.status, count(m.fms_id) projects
         from named_features n left join named_feature_matches m using (feature_id)
         group by all order by projects desc, n.feature_id""")

md("### Street lines (centerline)")
md("`extent`: the stretch of a street between two named cross streets, routed along the centerline (Tier A). "
   "`street_only`: a named street's segments inside the project's community district(s), capped at 5 km, "
   "or 2.5 km when only the borough is known (Tier B). Validation: distance from another Tier A source's "
   "point to the nearest point of the line; nothing was tuned on these projects.")
md()
sl_counts, sl_stats = street_line_agreement(con)
md("| kind | lines drawn | validated | median_m | within_200m | within_500m |")
md("|---|---|---|---|---|---|")
for kind in sorted(sl_counts):
    ds = sl_stats.get(kind, [])
    med = f"{ds[len(ds) // 2]:,.0f}" if ds else ""
    near200, near500 = sum(d <= 200 for d in ds), sum(d <= 500 for d in ds)
    md(f"| {kind} | {sl_counts[kind]:,} | {len(ds):,} | {med} | {near200:,} | {near500:,} |")
md()

md("### Projects located outside the five boroughs (latest snapshot)")
md("Distance is from the NYC bounding box. Map rule (`docs/ui-plan.md`): within 30 km, extend the map; "
   "beyond that, show an edge-of-map marker pointing toward the site.")
md()
lat0, lat1, lon0, lon1 = 40.47, 40.93, -74.27, -73.68
outside = con.execute(f"""select l.lat, l.lon, p.budget, l.matched_to from project_locations l
    join {latest_fms} p using (fms_id)
    where not (l.lat between {lat0} and {lat1} and l.lon between {lon0} and {lon1})""").fetchall()
groups: dict[str, list] = {"near (<= 30 km)": [0, 0.0, set()], "far (> 30 km)": [0, 0.0, set()]}
for lat, lon, budget, name in outside:
    d = haversine_m(lat, lon, min(max(lat, lat0), lat1), min(max(lon, lon0), lon1)) / 1000
    g = groups["near (<= 30 km)" if d <= 30 else "far (> 30 km)"]
    g[0] += 1
    g[1] += budget or 0
    g[2].add(name)
md("| group | projects | budget_bn | features |")
md("|---|---|---|---|")
for k, (n, b, names) in groups.items():
    md(f"| {k} | {n} | {b / 1e9:.1f} | {', '.join(sorted(x for x in names if x))} |")
md()

md("### Tier B validation")
md("The Tier B steps (facility code, then title name match) were run on projects that already have Tier A "
   "coordinates; a placement counts as correct if it lands within 500 m. The Parks tracker is the independent "
   "check (agency-supplied coordinates); CPDB rows are partly circular because DCP built some CPDB geometry "
   "from the same FacDB/Parks layers. Large sites (Rikers, Flushing Meadows, college campuses) can be correct "
   "yet more than 500 m from the reference point.")
md()
table("""select truth_source, count_if(eligible) n_eligible, count_if(matched) n_matched,
         count_if(distance_m <= 500) within_500m, count_if(distance_m <= 1000) within_1000m,
         round(100.0 * count_if(distance_m <= 500) / nullif(count_if(matched), 0), 1) precision_500m_pct
         from location_validation group by 1
         union all
         select 'ALL', count_if(eligible), count_if(matched), count_if(distance_m <= 500),
         count_if(distance_m <= 1000),
         round(100.0 * count_if(distance_m <= 500) / nullif(count_if(matched), 0), 1)
         from location_validation order by 1""")

md("By rule (`facility_code`: pipeline/facility_codes.py; the others: `acceptable()` in pipeline/locations.py). "
   "Shares are % of matched projects within each distance:")
md()
table("""select coalesce(rule, 'ALL') as rule, count(*) n_matched, median(distance_m)::int median_m,
         round(100.0 * count_if(distance_m <= 100) / count(*), 1) pct_100m,
         round(100.0 * count_if(distance_m <= 250) / count(*), 1) pct_250m,
         round(100.0 * count_if(distance_m <= 500) / count(*), 1) pct_500m,
         round(100.0 * count_if(distance_m <= 1000) / count(*), 1) pct_1000m
         from location_validation where matched group by rollup(rule) order by rule is null, 2 desc""")

md("### District agreement")
md("Share of placed points inside the one community district the project lists. This is independent of the "
   "Tier A comparison, so it also covers sources with few Tier A overlaps (FDNY units). The `community_board` "
   "field is itself noisy: agency-supplied points agree only 77-93%, and some DCAS energy programs list a "
   "placeholder district, so treat these as floors. District and whole-street placements agree by construction.")
md()
md("| source | n | in_listed_district | other_district | outside_all_districts | pct_in |")
md("|---|---|---|---|---|---|")
for src, (n_in, n_other, n_out) in sorted(district_agreement(con).items()):
    md(f"| {src} | {n_in + n_other + n_out:,} | {n_in:,} | {n_other:,} | {n_out:,} | "
       f"{100 * n_in / (n_in + n_other + n_out):.1f} |")
md()

md("### Neighborhood (Tier C) validation")
md("The neighborhood step run on projects with Tier A points: distance from the Tier A point to the named "
   "neighborhood's boundary (0 when inside). DOT and DEP projects are not placed this way.")
md()
table("""select coalesce(managing_agency, 'ALL') managing_agency, count(*) n,
         round(100.0 * count_if(distance_m = 0) / count(*), 1) pct_inside,
         round(100.0 * count_if(distance_m <= 500) / count(*), 1) pct_within_500m,
         round(100.0 * count_if(distance_m <= 1000) / count(*), 1) pct_within_1km
         from neighborhood_validation group by rollup(managing_agency)
         having count(*) >= 5 order by grouping(managing_agency) desc, n desc""")
md()

md("### Tier A cross-source agreement")
md("Projects present in more than one Tier A source: distance between source representative points.")
md()
reps = {}
for src, tbl in [("parks_tracker", "loc_parks_tracker"), ("cpdb_points", "loc_cpdb_points"),
                 ("cpdb_polygons", "loc_cpdb_polygons"), ("dot_intersections", "loc_dot_intersections")]:
    for fms, lon, lat in con.execute(f"select fms_id, avg(lon), avg(lat) from {tbl} group by 1").fetchall():
        reps.setdefault(fms, {})[src] = (lon, lat)
pairs: dict[str, list[float]] = {}
for srcs in reps.values():
    names = sorted(srcs)
    for i, a in enumerate(names):
        for b in names[i + 1:]:
            (lo1, la1), (lo2, la2) = srcs[a], srcs[b]
            pairs.setdefault(f"{a} vs {b}", []).append(haversine_m(la1, lo1, la2, lo2))
md("| sources | projects | median_m | within_500m |")
md("|---|---|---|---|")
for k, ds in sorted(pairs.items()):
    ds.sort()
    md(f"| {k} | {len(ds):,} | {ds[len(ds) // 2]:,.0f} | {sum(d <= 500 for d in ds):,} |")
md()

md("### Borough consistency (latest snapshot)")
md("Does the placed point fall inside a community district of the borough the project lists? Points in "
   "parkland/airports outside every district (joint interest areas) count as `outside_districts`.")
md()
cds = [(b, json.loads(g)) for b, g in con.execute("select borough, geojson from ref_community_districts").fetchall()]
check = con.execute(f"""select l.tier, p.borough, l.lon, l.lat from project_locations l
    join (select fms_id, any_value(borough) borough from project_budget_schedule
          where reporting_period={latest} group by 1) p using (fms_id)
    where l.tier in ('A', 'B')
      and p.borough in ('Manhattan', 'Bronx', 'Brooklyn', 'Queens', 'Staten Island')""").fetchall()
agg: dict[str, list[int]] = {}
for tier, boro, lon, lat in check:
    found = next((b for b, g in cds if contains(g, lon, lat)), None)
    s = agg.setdefault(tier, [0, 0, 0, 0])
    s[0] += 1
    s[1 if found == boro else 2 if found else 3] += 1
md("| tier | checked | same_borough | other_borough | outside_districts |")
md("|---|---|---|---|---|")
for tier, (n, same, other, outside) in sorted(agg.items()):
    md(f"| {tier} | {n:,} | {same:,} | {other:,} | {outside:,} |")
md()
md("**Summary:** Tiers A and B support a point map for the placed share; C, D and E support neighborhood, "
   "district and borough aggregation only; Citywide projects appear as a separate list.")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
sys.exit(0)
