"""Profile data/capital.duckdb and write docs/profile.md (coverage, join integrity, locations)."""
import sys
from pathlib import Path

import duckdb

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "data" / "capital.duckdb"
OUT = ROOT / "docs" / "profile.md"

TABLES = ["project_budget_schedule", "budget_spend_by_fy", "budget_history", "schedule_history"]
KEY_COLS = {
    "project_budget_schedule": ["pid", "fms_id", "managing_agency", "total_budget", "spend_to_date",
                                "current_phase", "forecast_completion", "borough", "community_board"],
    "budget_spend_by_fy": ["fms_id", "managing_agency", "fiscal_year", "total_budget_city_non_city", "spend"],
    "budget_history": ["fms_id", "managing_agency", "total_budget", "budget_variance", "budget_variance_pct"],
    "schedule_history": ["pid", "managing_agency", "completion_date", "variance_day"],
}
LOCATION_HINTS = ["lat", "lon", "lng", "geom", "the_geom", "location", "address", "bbl", "bin",
                  "borough", "community", "district", "zip", "x_coord", "y_coord", "council"]

con = duckdb.connect(str(DB_PATH), read_only=True)
lines: list[str] = []


def md(s: str = "") -> None:
    lines.append(s)


def table(sql: str) -> None:
    cur = con.execute(sql)
    cols = [d[0] for d in cur.description]
    rows = cur.fetchall()
    md("| " + " | ".join(cols) + " |")
    md("|" + "|".join("---" for _ in cols) + "|")
    plain = {i for i, c in enumerate(cols) if "period" in c or "year" in c or c == "pid" or c in ("first_period", "last_period")}
    for r in rows:
        md("| " + " | ".join(
            "" if v is None else
            str(v) if i in plain else
            f"{v:,}" if isinstance(v, int) else
            f"{v:,.2f}" if isinstance(v, float) else str(v)
            for i, v in enumerate(r)) + " |")
    md()


def scalar(sql: str):
    return con.execute(sql).fetchone()[0]


md("# Data profile")
md()
md("Generated by `pipeline/profile.py` from `data/capital.duckdb`. Re-run after each ingest.")
md()
md("## 1. Source freshness and row counts")
table("select table_name, dataset_id, source_rows_updated_at, remote_count, loaded_rows from _ingest_meta")

md("## 2. Coverage")
md("### Snapshots (reporting periods)")
md("`project_budget_schedule` and `budget_spend_by_fy` hold one full snapshot per reporting period "
   "(YYYYMM, Jan/May/Sep). `budget_history` is keyed by `year_month_reported`.")
md()
table("""select 'project_budget_schedule' t, min(reporting_period) first_period, max(reporting_period) last_period,
         count(distinct reporting_period) periods from project_budget_schedule
         union all select 'budget_spend_by_fy', min(reporting_period), max(reporting_period),
         count(distinct reporting_period) from budget_spend_by_fy
         union all select 'budget_history', min(year_month_reported), max(year_month_reported),
         count(distinct year_month_reported) from budget_history
         union all select 'schedule_history', min(reporting_period), max(reporting_period),
         count(distinct reporting_period) from schedule_history""")
md("### Per-period distinct projects (project_budget_schedule)")
table("""select reporting_period, count(*) n_rows, count(distinct fms_id) fms_ids, count(distinct pid) pids,
         round(100.0*count(pid)/count(*),1) pct_rows_with_pid from project_budget_schedule
         group by 1 order by 1""")
md("### Null rates for key columns (%)")
for t in TABLES:
    md(f"**{t}**")
    md()
    parts = ", ".join(f"round(100.0*count_if({c} is null)/count(*),1) as {c}" for c in KEY_COLS[t])
    table(f"select {parts} from {t}")
md("### Managing agencies in latest snapshot (top 15 by project count)")
table("""select managing_agency, count(distinct fms_id) fms_ids, sum(total_budget) total_budget
         from project_budget_schedule where reporting_period=(select max(reporting_period) from project_budget_schedule)
         group by 1 order by 2 desc limit 15""")

md("## 3. Join integrity")
latest = scalar("select max(reporting_period) from project_budget_schedule")
md(f"Latest snapshot used below: **{latest}**.")
md()
md("### Duplicate keys")
table(f"""select 'project_budget_schedule (fms_id, reporting_period)' as key_cols,
          count(*) - count(distinct (fms_id, reporting_period)) excess_rows from project_budget_schedule
          union all select 'budget_spend_by_fy (fms_id, fiscal_year, reporting_period)',
          count(*) - count(distinct (fms_id, fiscal_year, reporting_period)) from budget_spend_by_fy
          union all select 'budget_history (fms_id, year_month_reported)',
          count(*) - count(distinct (fms_id, year_month_reported)) from budget_history
          union all select 'schedule_history (pid, reporting_period)',
          count(*) - count(distinct (pid, reporting_period)) from schedule_history""")
md("### FMS ID overlap in the latest snapshot")
table(f"""with a as (select distinct fms_id from project_budget_schedule where reporting_period={latest}),
          b as (select distinct fms_id from budget_spend_by_fy where reporting_period={latest}),
          h as (select distinct fms_id from budget_history)
          select (select count(*) from a) in_project, (select count(*) from b) in_fy_spend,
                 (select count(*) from h) in_history_all_time,
                 (select count(*) from a join b using(fms_id)) project_and_fy,
                 (select count(*) from a anti join b using(fms_id)) project_not_in_fy,
                 (select count(*) from b anti join a using(fms_id)) fy_not_in_project,
                 (select count(*) from a anti join h using(fms_id)) project_not_in_history""")
md("### PID overlap (project_budget_schedule vs schedule_history), latest snapshot")
table(f"""with a as (select distinct pid from project_budget_schedule where reporting_period={latest} and pid is not null),
          s as (select distinct pid from schedule_history where reporting_period={latest})
          select (select count(*) from a) pids_in_project, (select count(*) from s) pids_in_schedule_history,
                 (select count(*) from a join s using(pid)) as n_matched,
                 (select count(*) from s anti join a using(pid)) schedule_pid_not_in_project""")
md("### PID <-> FMS ID cardinality (latest snapshot, rows with a PID)")
md("Many-to-many is confirmed if both maxima exceed 1. Only `project_budget_schedule` carries both keys, "
   "so it is the bridge between FMS-keyed budget data and PID-keyed schedule history.")
md()
table(f"""with m as (select distinct pid, fms_id from project_budget_schedule where reporting_period={latest} and pid is not null),
          pf as (select pid, count(*) n from m group by 1), fp as (select fms_id, count(*) n from m group by 1)
          select (select count(*) from m) pid_fms_pairs,
                 (select max(n) from pf) max_fms_per_pid, (select count_if(n>1) from pf) pids_with_multi_fms,
                 (select max(n) from fp) max_pid_per_fms, (select count_if(n>1) from fp) fms_with_multi_pid""")
md("### Rows with FMS ID but no PID (latest snapshot)")
table(f"""select count(*) rows_no_pid, count(distinct fms_id) fms_no_pid
          from project_budget_schedule where reporting_period={latest} and pid is null""")

md("### Fan-out warning: repeated FMS IDs in project_budget_schedule")
md("Repeated `fms_id` rows within a snapshot are one row per linked PID, not true duplicates. "
   "Most repeat the same budget, but some differ (see `repeated_with_differing_budget`), so de-duplication "
   "needs a rule (e.g. take the budget from `budget_spend_by_fy`/`budget_history`, which are FMS-keyed). "
   "Summing `total_budget` across rows without de-duplicating by `fms_id` double-counts. "
   "The dedup figure below uses an arbitrary row per FMS ID and is illustrative only.")
md()
table(f"""with d as (select fms_id, count(*) n, count(distinct total_budget) n_budgets
                    from project_budget_schedule where reporting_period={latest} group by 1)
          select count_if(n>1) fms_ids_repeated, max(n) max_rows_per_fms,
                 count_if(n>1 and n_budgets>1) repeated_with_differing_budget from d""")
table(f"""select round(sum(total_budget)) as naive_sum_all_rows,
          (select round(sum(b)) from (select any_value(total_budget) b from project_budget_schedule
             where reporting_period={latest} group by fms_id)) as dedup_sum_by_fms
          from project_budget_schedule where reporting_period={latest}""")

md("## 4. Variance sign sanity")
md("Variance must be reported signed. Confirm both signs exist so values were not stored as absolute.")
md()
table("""select 'budget_variance' col, count_if(budget_variance<0) negative, count_if(budget_variance=0) zero,
         count_if(budget_variance>0) positive, count_if(budget_variance is null) as n_null,
         min(budget_variance) as min_v, max(budget_variance) as max_v from budget_history
         union all select 'budget_variance_pct', count_if(budget_variance_pct<0), count_if(budget_variance_pct=0),
         count_if(budget_variance_pct>0), count_if(budget_variance_pct is null), min(budget_variance_pct),
         max(budget_variance_pct) from budget_history
         union all select 'variance_day', count_if(variance_day<0), count_if(variance_day=0),
         count_if(variance_day>0), count_if(variance_day is null), min(variance_day), max(variance_day)
         from schedule_history""")

md("### Outliers: implausible forecast dates in schedule_history")
md("Rows with |variance_day| > 3,650 (10 years) are almost certainly data-entry errors and should be excluded or clamped in the UI.")
md()
table("""select pid, completion_date, completion_date_type, variance_day from schedule_history
         where abs(variance_day) > 3650 order by abs(variance_day) desc""")

md("## 5. Location availability")
md("Columns in any table whose name hints at a location:")
md()
hits = con.execute("""select table_name, column_name, data_type from information_schema.columns
                      where table_name in (select table_name from _ingest_meta)""").fetchall()
loc = [h for h in hits if any(k in h[1].lower() for k in LOCATION_HINTS)]
md("| table | column | type |")
md("|---|---|---|")
for t, c, d in loc:
    md(f"| {t} | {c} | {d} |")
md()
md(f"### Borough and community board fill (latest snapshot)")
table(f"""select borough, count(*) n_rows, count_if(community_board is null) no_board,
          count(distinct community_board) distinct_boards from project_budget_schedule
          where reporting_period={latest} group by 1 order by 2 desc""")
md("### Community board granularity")
table(f"""select count_if(community_board ilike '%citywide%') citywide, count_if(community_board is null) null_board,
          count_if(community_board not ilike '%citywide%' and community_board is not null) specific_board,
          count(*) total from project_budget_schedule where reporting_period={latest}""")
md("**Verdict:** there are no coordinates, addresses, BBL/BIN or geometry columns in any of the four datasets. "
   "Location is limited to `borough` and `community_board` (text such as `Manhattan 01`, sometimes multi-valued, "
   "e.g. `Manhattan, Manhattan 03`) and `Citywide`. A point map is not possible from these sources; "
   "a community-district or borough choropleth is (needs a boundary file, a new external asset to decide on). "
   "Citywide projects cannot be placed on any map.")

OUT.write_text("\n".join(lines) + "\n")
print(f"wrote {OUT}")
sys.exit(0)
